spring:
  profiles:
    active: ${APP_PROFILE:dev}
  application:
    name: match-movie

  threads:
    virtual:
      enabled: true

  flyway:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate

  messages:
    basename: i18n/messages
    encoding: UTF-8
    fallback-to-system-locale: false